### ISSUE TITLE
User actions are being dropped for Android devices with "no side effect was registered during its scope" notice

### ISSUE THREAD

**Issue by xacaciax** [GetDutchie/datadog_flutter#53]
We recently added this package to our mobile applications to track page views and user actions. The same user actions that are registering and being reported to datadog for an iOS mobile device are getting dropped on Android devices. 

This same action that is coming through and viewable in datadog for an iOS device (iPhone 12 in the XCode simulator) 

![image](https://user-images.githubusercontent.com/82327972/133865802-5f167cda-13a6-48ef-bc4b-123db2ab75e5.png)

is getting dropped on an Android device (Pixel 5 API 31 in Andoid Studio emulator) with the error: 

`I/Datadog (26349): RUM Action fe7e6881-dfc3-46a6-a170-fa44f6f0b06a (TAP on housingServiceFavorited) was dropped (no side effect was registered during its scope)
`

<img width="978" alt="Screen Shot 2021-09-17 at 5 30 41 PM" src="https://user-images.githubusercontent.com/82327972/133865869-ee3c7178-ee75-41c2-8370-1bfc68bbc134.png">

I double checked my configuration and my `androidRumApplicationId` is correct. Views and other data is reporting as expected. 

This log message `no side effect was registered during its scope` can be found in the [dd-sdk-android](https://github.com/DataDog/dd-sdk-android/blob/ebf18915ddf5c6ddd2ef68f467fdef8cc33cdaee/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt#L224). 

We are glad to be using this package and looking forward to a resolution here 🙏🏼

**Comment by tshedor** [comment]
Hey @xacaciax thanks for using `datadog_flutter`. To be honest, I'm out of my depth on this one because I primarily work in iOS. 

Doing a bit of searching, I found a thread that suggests dropping `tap` events is a...[feature not a bug](https://github.com/DataDog/dd-sdk-android/issues/484#issuecomment-771659922)? This, however, doesn't make sense, because there wouldn't be a Tap API if the SDK developers didn't intend the end implementation to use it. 

There was [one other caveat in the same thread](https://github.com/DataDog/dd-sdk-android/issues/484#issuecomment-819115629) that I'd like you to check on your emulator for me. 

Otherwise, it appears the [SDK purposefully ignores events](https://github.com/DataDog/dd-sdk-android/blob/ebf18915ddf5c6ddd2ef68f467fdef8cc33cdaee/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt#L231) that are not `custom`. So could you also please try changing this event type to `custom` and seeing if it reports the same for iOS and Android?

**Comment by xacaciax** [comment]
@tshedor thanks so much for responding here. I checked the battery level on my emulator and set it to 100% and that didn't seem to be the cause. Then, I changed the event type to `RUMAction.custom` and the SDK stopped dropping the action. 
![image](https://user-images.githubusercontent.com/82327972/134041100-1ec950ea-dbea-465b-97f8-0909ae61e3f9.png) 
Strange that the Android SDK is only registering custom events 🤔  But nonetheless, this will work for us. Here's the event coming through from the Android emulator 🥳 Thanks!!

**Comment by tshedor** [comment]
@xacaciax super strange. I've reached out directly to the RUM team about this and will hopefully report back with a better work around than having all your events be custom.

**Comment by xgouchet** [comment]
Hi @xacaciax, actually the SDK does register TAP events but for now we only keep them if they have a noticeable side effect. This was originally done to avoid adding too much noise registering events that didn't lead to errors or network resources.

**Comment by tshedor** [comment]
Thanks for responding @xgouchet . @xacaciax I'm going to open a PR to include this in the README
